/** Kernel primitives every component builds on (SCRIPT_MODEL §4.1). */
export const CORE_PRIMITIVE_TYPES = ['box', 'button', 'webService'] as const;

/**
 * Library components shipped by `@verbis/components` (roadmap step 27). The validator treats
 * these plus `componentRegistry` entries as known; callers can pass a narrower or wider set.
 */
export const LIBRARY_COMPONENT_TYPES = [
  'text',
  'heading',
  'scriptText',
  'privacyNotice',
  'explicitConsent',
  'richContent',
  'alert',
  'divider',
  'textInput',
  'textArea',
  'numberInput',
  'maskedInput',
  'select',
  'radioGroup',
  'checkbox',
  'datePicker',
  'table',
  'tabs',
  'dispositionPicker',
  'timer',
  'callout',
  'objectionHandler',
  'checklist',
  'knowledgeLink',
  'currencyInput',
  'multiSelect',
  'checkboxGroup',
  'toggle',
  'timePicker',
  'rating',
  'slider',
  'phoneInput',
  'emailInput',
  'addressInput',
  'tcknInput',
  'vknInput',
  'ibanInput',
  'creditCardInput',
  'section',
  'card',
  'columns',
  'accordion',
  'stepper',
  'wizard',
  'modal',
  'spacer',
  'repeater',
  'lookup',
  'autoComplete',
  'dataGrid',
  'keyValueList',
  'customerCard',
  'timeline',
  'chart',
  'actionButton',
  'nextButton',
  'backButton',
  'buttonGroup',
  'outcomeSubmit',
  'transferHint',
  'callbackScheduler',
  'image',
  'video',
  'iframe',
  'countdown',
  'note',
  'badge',
  'progressIndicator',
  'signature',
] as const;

export const BUILTIN_COMPONENT_TYPES: readonly string[] = [
  ...CORE_PRIMITIVE_TYPES,
  ...LIBRARY_COMPONENT_TYPES,
];

/** Props that would carry display text; they must be `*Key` i18n references instead. */
export const LITERAL_TEXT_PROPS: readonly string[] = [
  'text',
  'label',
  'title',
  'placeholder',
  'helperText',
  'description',
  'content',
  'message',
];
