/**
 * Every enum value the admin workspace renders. Each needs
 * `adminWorkspace.enum.<name>.<value>` in the TR and EN catalogs (U-02, enforced by enums.spec).
 */
export const ADMIN_ENUMS = {
  status: [
    'draft',
    'active',
    'disabled',
    'error',
    'invited',
    'suspended',
    'deprovisioned',
    'provisioning',
    'deleting',
    'pending_mfa',
  ],
  protocol: ['oidc', 'saml', 'local'],
  adapterType: [
    'generic',
    'genesys_cloud',
    'genesys_engage',
    'avaya_aes',
    'avaya_axp',
    'avaya_aacc',
    'amazon_connect',
    'cisco',
    'nice_cxone',
    'five9',
  ],
  ctiPlatform: [
    'amazon-connect',
    'cisco',
    'nice-cxone',
    'five9',
    'generic',
    'genesys-cloud',
    'genesys-engage',
    'avaya-aes',
    'avaya-axp',
    'avaya-aacc',
  ],
  ctiKind: ['queue', 'campaign', 'skill', 'vdn', 'routingPoint', 'flow', 'dnis'],
  outcome: ['success', 'denied', 'failure'],
  secretKind: ['password', 'api_key', 'oauth_client', 'certificate', 'generic'],
  siemKind: ['webhook', 'syslog', 'kafka'],
  siemFormat: ['rfc5424', 'cef', 'json'],
  privacyKind: ['search', 'export', 'anonymize'],
  privacyState: ['pending', 'completed', 'blocked'],
  sessionLimit: ['evict_oldest', 'deny'],
  classification: ['public', 'internal', 'pii', 'pci'],
  roleSource: ['manual', 'sso', 'jit', 'scim', 'asc'],
  resource: [
    'campaign',
    'script',
    'screen',
    'integration',
    'secret',
    'connector',
    'user',
    'role',
    'idp',
    'audit',
    'report',
    'session',
  ],
  action: [
    'read',
    'create',
    'update',
    'delete',
    'publish',
    'approve',
    'execute',
    'reveal',
    'export',
    'manage',
  ],
  scope: ['all', 'campaign', 'team', 'site', 'own'],
} as const;
export type AdminEnum = keyof typeof ADMIN_ENUMS;

/** List columns whose values are enums by default; call sites override ambiguous ones (`kind`). */
export const ENUM_COLUMNS: Readonly<Record<string, AdminEnum>> = {
  status: 'status',
  protocol: 'protocol',
  adapterType: 'adapterType',
  outcome: 'outcome',
};
