// Examples are authored data. Their execution belongs to the test suite, never the generator.
export const expressionExamples = {
  upper: ['upper("verbis")', 'VERBIS'],
  lower: ['lower("VERBIS")', 'verbis'],
  trim: ['trim("  demo  ")', 'demo'],
  contains: ['contains([1,2,3], 2)', true],
  startsWith: ['startsWith("demo-script", "demo")', true],
  format: ['format("Hello {0}", "Demo")', 'Hello Demo'],
  mask: ['mask("DEMO-REF", 3)', '*****REF'],
  padStart: ['padStart("7", 3, "0")', '007'],
  round: ['round(12.345, 2)', 12.35],
  formatCurrency: ['formatCurrency(1500, "tr", "TRY")', '1.500,00 ₺'],
  now: ['now()', '2026-10-03T09:00:00.000Z'],
  addDays: ['addDays("2026-10-03", 2)', '2026-10-05T00:00:00.000Z'],
  diff: ['diff("2026-10-05", "2026-10-03", "days")', 2],
  formatDate: ['formatDate("2026-10-03", "dd.MM.yyyy")', '03.10.2026'],
  isBusinessDay: ['isBusinessDay("2026-10-05", [])', true],
  age: ['age("2000-01-01", "2026-10-03")', 26],
  count: ['count([1,2,3])', 3],
  sum: ['sum([{amount:10},{amount:20}], x => x.amount)', 30],
  filter: ['filter([1,2,3], x => x > 1)', [2, 3]],
  map: ['map([1,2], x => x * 2)', [2, 4]],
  find: ['find([1,2,3], x => x > 1)', 2],
  any: ['any([1,2], x => x > 1)', true],
  all: ['all([1,2], x => x > 0)', true],
  isEmail: ['isEmail("demo@example.invalid")', true],
  isPhoneTR: ['isPhoneTR("invalid")', false],
  isTCKN: ['isTCKN("invalid")', false],
  isIBAN: ['isIBAN("invalid")', false],
  isVKN: ['isVKN("invalid")', false],
  luhn: ['luhn("invalid")', false],
  regexTest: ['regexTest("demo-42", "^demo-[0-9]+$")', true],
  if: ['if(true, "yes", "no")', 'yes'],
  switch: ['switch("gold", "gold", 10, 0)', 10],
  exists: ['exists(null)', false],
  between: ['between(5, [1,10])', true],
  before: ['before("2026-10-03", "2026-10-05")', true],
  after: ['after("2026-10-05", "2026-10-03")', true],
  toNumber: ['toNumber("42")', 42],
  toString: ['toString(42)', '42'],
  parseJSON: ['parseJSON("{\\"ok\\":true}")', { ok: true }],
};

export const connectorGuides = [
  ['genesys-cloud', 'Genesys Cloud', 'genesys-cloud.md', 'cloud'],
  ['genesys-engage', 'Genesys Engage', 'genesys-engage.md', 'workspace / sidecar'],
  ['avaya-aes', 'Avaya AES', 'avaya.md', 'sidecar'],
  ['avaya-axp', 'Avaya AXP', 'avaya.md', 'workspaces'],
  ['avaya-aacc', 'Avaya AACC', 'avaya.md', 'sidecar'],
  ['amazon-connect', 'Amazon Connect', 'amazon-connect.md', 'contact-events'],
  ['cisco-webex', 'Cisco Webex Contact Center', 'cisco-webex.md', 'desktop-widget'],
  ['cisco-finesse', 'Cisco UCCE/PCCE Finesse', 'cisco-finesse.md', 'finesse-gadget'],
  ['nice-cxone', 'NICE CXone', 'nice-cxone.md', 'agent-api'],
  ['five9', 'Five9', 'five9.md', 'desktop-toolkit'],
  ['salesforce', 'Salesforce Open CTI', 'salesforce.md', 'salesforce-open-cti'],
  ['dynamics-365', 'Dynamics 365 CIF', 'dynamics-365.md', 'dynamics-cif'],
];
