{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: {{ .name }} }
spec:
  refreshInterval: 1h
  secretStoreRef: {{ toYaml $.Values.externalSecrets.storeRef | nindent 4 }}
  target: { name: {{ .name }}, creationPolicy: Owner }
  data: {{ toYaml .data | nindent 4 }}
{{- end }}
{{- end }}
