import type { ScriptDocumentInput } from '../schema/document.js';

/** Telecom tariff change: OTP verification subflow → current plan → catalog → confirm → apply. */
export const telecomTariffChangeScript: ScriptDocumentInput = {
  schemaVersion: '1.1.0',
  id: '01928f3a-0000-7000-8000-000000000002',
  meta: {
    name: 'Tarife Değişikliği',
    tags: ['telecom', 'retention'],
    channels: ['voice', 'chat'],
    capabilities: ['transfer'],
  },
  variables: [
    {
      key: 'msisdn',
      type: 'string',
      scope: 'interaction',
      classification: 'pii',
      pii: true,
      source: 'interaction.ani',
    },
    { key: 'currentTariff', type: 'string', scope: 'session', persist: true },
    {
      key: 'selectedTariff',
      type: 'enum',
      scope: 'session',
      enumValues: ['S20', 'S40', 'UNL'],
      persist: true,
    },
    { key: 'otpCode', type: 'string', scope: 'page' },
    { key: 'otpAttempts', type: 'number', scope: 'session', default: 0 },
    { key: 'otpValid', type: 'boolean', scope: 'session', default: false, persist: true },
    { key: 'tariffChangeConfirmed', type: 'boolean', scope: 'page', default: false },
    { key: 'effectiveDate', type: 'date', scope: 'session', persist: true },
    { key: 'orderId', type: 'string', scope: 'session', classification: 'internal' },
    {
      key: 'campaignDiscount',
      type: 'number',
      scope: 'campaign',
      default: 10,
      classification: 'public',
    },
  ],
  dataSources: [
    {
      id: 'sendOtp',
      ref: 'tenant-datasource:otp-send',
      version: 1,
      inputs: { msisdn: { $expr: 'vars.msisdn' } },
    },
    {
      id: 'verifyOtp',
      ref: 'tenant-datasource:otp-verify',
      version: 1,
      inputs: { msisdn: { $expr: 'vars.msisdn' }, code: { $expr: 'vars.otpCode' } },
      outputs: { valid: { path: '$.valid', variable: 'otpValid' } },
    },
    {
      id: 'subscriberInfo',
      ref: 'tenant-datasource:subscriber-info',
      version: 3,
      inputs: { msisdn: { $expr: 'vars.msisdn' } },
      outputs: {
        tariff: { path: '$.data.tariff.code', variable: 'currentTariff' },
        usage: { path: '$.data.usage' },
        contractEnd: { path: '$.data.contract.endDate' },
      },
      policy: { trigger: 'manual', cacheTtlSec: 30 },
    },
    {
      id: 'tariffCatalog',
      ref: 'tenant-datasource:tariff-catalog',
      version: 2,
      inputs: { current: { $expr: 'vars.currentTariff' } },
      outputs: { offers: { path: '$.data.offers' } },
      policy: { cacheTtlSec: 300 },
    },
    {
      id: 'changeTariff',
      ref: 'tenant-datasource:tariff-change',
      version: 1,
      inputs: { msisdn: { $expr: 'vars.msisdn' }, tariff: { $expr: 'vars.selectedTariff' } },
      // Mapped into an internal variable so it may be written back to the platform: raw data
      // source results count as personal data and may not reach platform sinks.
      outputs: { orderId: { path: '$.orderId', variable: 'orderId' } },
      policy: { timeoutMs: 15000 },
    },
  ],
  pages: [
    {
      id: 'identify',
      name: 'Tanışma',
      titleKey: 'identify.title',
      layout: {
        id: 'identify-root',
        type: 'box',
        style: { base: { direction: 'column', gap: 'md', padding: 'md' } },
        children: [
          { id: 'identify-text', type: 'scriptText', props: { textKey: 'identify.text' } },
          {
            id: 'btn-identify-next',
            type: 'button',
            props: { variant: 'primary', labelKey: 'common.next' },
            events: { onPress: [{ type: 'next' }] },
          },
        ],
      },
    },
    {
      id: 'otp',
      name: 'OTP',
      titleKey: 'otp.title',
      timers: [
        {
          id: 'otp-expiry',
          durationMs: 180000,
          autoStart: true,
          onElapsed: [{ type: 'showToast', messageKey: 'otp.expired', tone: 'warning' }],
        },
      ],
      layout: {
        id: 'otp-root',
        type: 'box',
        style: { base: { direction: 'column', gap: 'md', padding: 'md' } },
        children: [
          {
            id: 'in-otp',
            type: 'textInput',
            props: {
              labelKey: 'otp.code',
              maxLength: 6,
            },
            bindings: [{ variable: 'otpCode' }],
            // The code is page-scoped and cleared on leaving; once verified it is no longer needed,
            // or the final outcome would fail script-wide validation.
            requiredWhen: { $expr: '!vars.otpValid' },
          },
          {
            id: 'btn-otp-verify',
            type: 'button',
            props: { variant: 'primary', labelKey: 'otp.verify' },
            events: {
              onPress: [
                {
                  type: 'callDataSource',
                  dataSource: 'verifyOtp',
                  onSuccess: [{ type: 'stopTimer', timer: 'otp-expiry' }, { type: 'next' }],
                  onError: [
                    {
                      type: 'sequence',
                      actions: [
                        {
                          type: 'setVariable',
                          variable: 'otpAttempts',
                          value: { $expr: 'vars.otpAttempts + 1' },
                        },
                        {
                          type: 'showToast',
                          messageKey: 'otp.invalid',
                          tone: 'danger',
                          params: { left: { $expr: '3 - vars.otpAttempts' } },
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          },
        ],
      },
    },
    {
      id: 'current-plan',
      name: 'Mevcut Tarife',
      titleKey: 'current.title',
      layout: {
        id: 'current-root',
        type: 'box',
        style: { base: { direction: 'column', gap: 'md', padding: 'md' } },
        children: [
          {
            id: 'current-summary',
            type: 'text',
            props: { textKey: 'current.summary' },
            bindings: [
              {
                prop: 'params',
                expression: '{ tariff: vars.currentTariff, end: ds.subscriberInfo.contractEnd }',
              },
            ],
          },
          {
            id: 'usage-table',
            type: 'table',
            props: {
              labelKey: 'current.usageCaption',
              columns: [
                { field: 'type', labelKey: 'current.usageType' },
                { field: 'used', labelKey: 'current.usageUsed' },
              ],
            },
            bindings: [{ prop: 'rows', expression: 'ds.subscriberInfo.usage' }],
          },
          {
            id: 'btn-current-next',
            type: 'button',
            props: { variant: 'primary', labelKey: 'common.next' },
            events: { onPress: [{ type: 'next' }] },
          },
        ],
      },
    },
    {
      id: 'catalog',
      name: 'Tarife Seçimi',
      titleKey: 'catalog.title',
      onEnter: [
        {
          type: 'callDataSource',
          dataSource: 'tariffCatalog',
          onError: [{ type: 'showToast', messageKey: 'catalog.loadFailed', tone: 'danger' }],
        },
      ],
      layout: {
        id: 'catalog-root',
        type: 'box',
        style: { base: { direction: 'column', gap: 'md', padding: 'md' } },
        children: [
          {
            id: 'in-tariff',
            type: 'radioGroup',
            props: { labelKey: 'catalog.choose' },
            bindings: [
              { prop: 'options', expression: 'ds.tariffCatalog.offers' },
              { variable: 'selectedTariff' },
            ],
          },
          {
            id: 'catalog-discount',
            type: 'alert',
            props: { textKey: 'catalog.discount', tone: 'success' },
            bindings: [{ prop: 'params', expression: '{ discount: vars.campaignDiscount }' }],
            visibleWhen: { $expr: 'vars.campaignDiscount > 0' },
          },
          {
            id: 'catalog-actions',
            type: 'box',
            style: { base: { direction: 'row', justify: 'between' } },
            children: [
              {
                id: 'btn-catalog-back',
                type: 'button',
                props: { labelKey: 'common.back' },
                events: { onPress: [{ type: 'back' }] },
              },
              {
                id: 'btn-catalog-next',
                type: 'button',
                props: { variant: 'primary', labelKey: 'common.next' },
                enabledWhen: { $expr: 'vars.selectedTariff != null' },
                events: { onPress: [{ type: 'next' }] },
              },
            ],
          },
        ],
      },
    },
    {
      id: 'confirm',
      name: 'Onay',
      titleKey: 'confirm.title',
      mandatory: true,
      layout: {
        id: 'confirm-root',
        type: 'box',
        style: { base: { direction: 'column', gap: 'md', padding: 'md' } },
        children: [
          {
            id: 'confirm-text',
            type: 'scriptText',
            props: { textKey: 'confirm.text' },
            bindings: [
              {
                prop: 'params',
                expression: '{ from: vars.currentTariff, to: vars.selectedTariff }',
              },
            ],
          },
          {
            id: 'in-confirm',
            type: 'checkbox',
            props: { labelKey: 'confirm.checkbox' },
            bindings: [{ prop: 'checked', variable: 'tariffChangeConfirmed' }],
          },
          {
            id: 'btn-reverify',
            type: 'button',
            props: { variant: 'secondary', labelKey: 'confirm.reverify' },
            events: { onPress: [{ type: 'runSubflow', flow: 'verify-otp' }] },
          },
          {
            id: 'btn-confirm-next',
            type: 'button',
            props: { variant: 'primary', labelKey: 'common.next' },
            events: { onPress: [{ type: 'next' }] },
          },
        ],
      },
    },
    {
      id: 'done',
      name: 'Tamamlandı',
      titleKey: 'done.title',
      onEnter: [
        { type: 'setDisposition', code: 'TARIFF_CHANGED' },
        {
          type: 'writeBackToPlatform',
          attributes: {
            'tariff.new': { $expr: 'vars.selectedTariff' },
            'tariff.order': { $expr: 'vars.orderId' },
          },
        },
      ],
      layout: {
        id: 'done-root',
        type: 'box',
        children: [
          {
            id: 'done-text',
            type: 'scriptText',
            props: { textKey: 'done.text' },
            bindings: [{ prop: 'params', expression: '{ date: vars.effectiveDate }' }],
          },
          {
            id: 'btn-done',
            type: 'button',
            props: { variant: 'primary', labelKey: 'common.finish' },
            events: {
              onPress: [{ type: 'submitOutcome', outcome: 'TARIFF_CHANGED' }, { type: 'next' }],
            },
          },
        ],
      },
    },
    {
      id: 'transfer',
      name: 'Teknik Destek Aktarımı',
      titleKey: 'transfer.title',
      onEnter: [
        { type: 'transferHint', target: 'TECH_SUPPORT', reasonKey: 'transfer.reason' },
        { type: 'setDisposition', code: 'TRANSFERRED' },
      ],
      layout: {
        id: 'transfer-root',
        type: 'box',
        children: [
          { id: 'transfer-text', type: 'scriptText', props: { textKey: 'transfer.text' } },
          {
            id: 'btn-transfer-done',
            type: 'button',
            props: { labelKey: 'common.finish' },
            events: { onPress: [{ type: 'next' }] },
          },
        ],
      },
    },
  ],
  flow: {
    id: 'main',
    start: 'n-identify',
    nodes: [
      { id: 'n-identify', type: 'page', page: 'identify' },
      { id: 'n-verify', type: 'subflow', flow: 'verify-otp' },
      { id: 'n-verified', type: 'decision' },
      { id: 'n-info', type: 'dataSource', dataSource: 'subscriberInfo' },
      { id: 'n-current', type: 'page', page: 'current-plan' },
      { id: 'n-catalog', type: 'page', page: 'catalog' },
      { id: 'n-confirm', type: 'page', page: 'confirm' },
      { id: 'n-confirmed', type: 'decision' },
      { id: 'n-apply', type: 'dataSource', dataSource: 'changeTariff' },
      {
        id: 'n-mark-date',
        type: 'setVariable',
        variable: 'effectiveDate',
        value: { $expr: 'now()' },
      },
      { id: 'n-done', type: 'page', page: 'done' },
      { id: 'n-transfer', type: 'page', page: 'transfer' },
      { id: 'n-end-ok', type: 'end', outcome: 'TARIFF_CHANGED' },
      { id: 'n-end-transfer', type: 'end', outcome: 'TRANSFERRED', completion: 'early' },
    ],
    edges: [
      { id: 'e1', from: 'n-identify', to: 'n-verify' },
      { id: 'e2', from: 'n-verify', to: 'n-verified' },
      { id: 'e3', from: 'n-verified', to: 'n-info', when: { $expr: 'vars.otpValid' } },
      { id: 'e4', from: 'n-verified', to: 'n-transfer', default: true },
      { id: 'e5', from: 'n-info', to: 'n-current', port: 'success' },
      { id: 'e6', from: 'n-info', to: 'n-transfer', port: 'error' },
      { id: 'e7', from: 'n-current', to: 'n-catalog' },
      { id: 'e8', from: 'n-catalog', to: 'n-confirm' },
      { id: 'e9', from: 'n-confirm', to: 'n-confirmed' },
      {
        id: 'e10',
        from: 'n-confirmed',
        to: 'n-apply',
        when: { $expr: 'vars.tariffChangeConfirmed == true' },
      },
      { id: 'e11', from: 'n-confirmed', to: 'n-catalog', default: true, maxIterations: 3 },
      { id: 'e12', from: 'n-apply', to: 'n-mark-date', port: 'success' },
      { id: 'e13', from: 'n-apply', to: 'n-transfer', port: 'error' },
      { id: 'e14', from: 'n-mark-date', to: 'n-done' },
      { id: 'e15', from: 'n-done', to: 'n-end-ok' },
      { id: 'e16', from: 'n-transfer', to: 'n-end-transfer' },
    ],
    limits: { maxSteps: 100 },
  },
  subflows: [
    {
      id: 'verify-otp',
      name: 'OTP doğrulama',
      start: 's-send',
      nodes: [
        { id: 's-send', type: 'dataSource', dataSource: 'sendOtp' },
        { id: 's-otp', type: 'page', page: 'otp' },
        { id: 's-check', type: 'decision' },
        { id: 's-ok', type: 'end' },
        { id: 's-fail', type: 'end', outcome: 'OTP_FAILED' },
      ],
      edges: [
        { id: 's-e1', from: 's-send', to: 's-otp', port: 'success' },
        { id: 's-e2', from: 's-send', to: 's-fail', port: 'error' },
        { id: 's-e3', from: 's-otp', to: 's-check' },
        { id: 's-e4', from: 's-check', to: 's-ok', when: { $expr: 'vars.otpValid' } },
        {
          id: 's-e5',
          from: 's-check',
          to: 's-send',
          when: { $expr: 'vars.otpAttempts < 3' },
          maxIterations: 3,
        },
        { id: 's-e6', from: 's-check', to: 's-fail', default: true },
      ],
    },
  ],
  rules: [],
  i18n: {
    defaultLocale: 'tr',
    messages: {
      tr: {
        'common.next': 'İleri',
        'common.back': 'Geri',
        'common.finish': 'Bitir',
        'identify.title': 'Tanışma',
        'identify.text': 'Tarife değişikliği talebiniz için güvenlik doğrulaması yapacağım.',
        'otp.title': 'Tek kullanımlık şifre',
        'otp.code': 'SMS ile gelen kod',
        'otp.verify': 'Kodu doğrula',
        'otp.invalid': 'Kod hatalı. Kalan deneme: {left}',
        'otp.expired': 'Kodun süresi doldu, yeniden gönderin.',
        'current.title': 'Mevcut tarife',
        'current.summary': 'Mevcut tarifeniz {tariff}, taahhüt bitişi {end}.',
        'current.usageCaption': 'Son 3 ay kullanım',
        'current.usageType': 'Tür',
        'current.usageUsed': 'Kullanım',
        'catalog.title': 'Yeni tarife',
        'catalog.choose': 'Tarife seçin',
        'catalog.discount': 'Kampanya indirimi: %{discount}',
        'catalog.loadFailed': 'Tarife listesi yüklenemedi.',
        'confirm.title': 'Onay',
        'confirm.text': '{from} tarifenizden {to} tarifesine geçişi onaylıyor musunuz?',
        'confirm.checkbox': 'Abone değişikliği onayladı',
        'confirm.reverify': 'Yeniden doğrula',
        'done.title': 'Tamamlandı',
        'done.text': 'Yeni tarifeniz {date} tarihinde geçerli olacak.',
        'transfer.title': 'Aktarım',
        'transfer.text': 'Sizi teknik destek ekibimize aktarıyorum.',
        'transfer.reason': 'Abone bilgisi alınamadı veya doğrulama başarısız.',
      },
      en: {
        'common.next': 'Next',
        'common.back': 'Back',
        'common.finish': 'Finish',
        'identify.title': 'Introduction',
        'identify.text': 'I will run a security check for your tariff change request.',
        'otp.title': 'One-time password',
        'otp.code': 'Code received by SMS',
        'otp.verify': 'Verify code',
        'otp.invalid': 'Wrong code. Attempts left: {left}',
        'otp.expired': 'The code has expired; send a new one.',
        'current.title': 'Current plan',
        'current.summary': 'Your current plan is {tariff}; commitment ends {end}.',
        'current.usageCaption': 'Usage in the last 3 months',
        'current.usageType': 'Type',
        'current.usageUsed': 'Used',
        'catalog.title': 'New plan',
        'catalog.choose': 'Choose a plan',
        'catalog.discount': 'Campaign discount: {discount}%',
        'catalog.loadFailed': 'Could not load the plan list.',
        'confirm.title': 'Confirmation',
        'confirm.text': 'Do you confirm switching from {from} to {to}?',
        'confirm.checkbox': 'Subscriber confirmed the change',
        'confirm.reverify': 'Verify again',
        'done.title': 'Done',
        'done.text': 'Your new plan takes effect on {date}.',
        'transfer.title': 'Transfer',
        'transfer.text': 'I am transferring you to our technical support team.',
        'transfer.reason': 'Subscriber lookup or verification failed.',
      },
    },
  },
};
